name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  check-schemas:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: graphql-inspector
        uses: kamilkisiela/graphql-inspector@main
        with:
          github-token: ${{ secrets.GITHUBTOKEN }}
          schema: "master:schema.graphqls"
            #    notifications:
            # slack: 'https://hooks.slack.com/services/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'
